on:
  push:
    branches: main

  schedule:
    - cron: '0 10 * * 0'
    - cron: '0 10 * * 1'
    - cron: '0 10 * * 2'
    - cron: '0 10 * * 3'
    - cron: '0 10 * * 4'
    - cron: '0 10 * * 5'
    - cron: '0 10 * * 6'
    - cron: '0 14 * * 0'
    - cron: '0 14 * * 1'
    - cron: '0 14 * * 2'
    - cron: '0 14 * * 3'
    - cron: '0 14 * * 4'
    - cron: '0 14 * * 5'
    - cron: '0 14 * * 6'
    - cron: '0 16 * * 0'
    - cron: '0 16 * * 1'
    - cron: '0 16 * * 2'
    - cron: '0 16 * * 3'
    - cron: '0 16 * * 4'
    - cron: '0 16 * * 5'
    - cron: '0 16 * * 6'

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest
            any::dplyr
            any::tidyr
            any::tidyverse
            any::stringr
            any::gt
            any::readr
            any::gtExtras
            any::lubridate
            any::webshot2
            any::png
            any::jsonlite
            any::httr
            any::janitor
            any::gsheet
            any::purrr
            any::shiny
            any::reactable
            any::xml2
            any::XML
            any::mlbplotR
            any::baseballr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("mlb_player_props.R")'

      - name: Commit results
        run: |
          git pull origin
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add MLB_Player_Props.png
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
