on:
#  push:
#    branches: main

#  schedule:
#    - cron: '0 08 * * *'
#    - cron: '0 10 * * *'
#    - cron: '0 12 * * *'
#    - cron: '0 14 * * *'
#    - cron: '0 16 * * *'
#    - cron: '0 18 * * *'

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest
            any::dplyr
            any::tidyr
            any::tidyverse
            any::stringr
            any::gt
            any::readr
            any::gtExtras
            any::lubridate
            any::webshot2
            any::png
            any::jsonlite
            any::httr
            any::janitor
            any::hoopR
            
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("nba_player_props.R")'

      - name: Commit results
        run: |
          git pull origin
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add NBA_Player_Props.png
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
